codecov:
  notify:
    after_n_builds: 11

comment:
  after_n_builds: 11

coverage:
  status:
    project:
      tests:
        paths:
          - "tests/"
        target: 100%
      source:
        paths:
          - "src/jupytext/"
        target: 97%
        threshold: 0.002
    patch:
      default:
        target: 80%  # new contributions should have a coverage at least equal to target
