codecov:
  notify:
    after_n_builds: 15

comment:
  after_n_builds: 15

coverage:
  status:
    project:
      source:
        paths:
          - "src/jupytext/"
        target: 97%
        threshold: 0.002
      tests:
        paths:
          - "tests/"
        target: 100%
      unit-tests:
        flags:
          - unit
      functional-tests:
        flags:
          - functional
      integration-tests:
        flags:
          - integration
      external-tests:
        flags:
          - external
    patch:
      default:
        target: 80%  # new contributions should have a coverage at least equal to target
