- id: jupytext
  name: jupytext
  description: Runs jupytext on all notebooks and paired files.
  language: python
  entry: jupytext --ignore-unmatched --alert-untracked
  require_serial: true
  types: [jupyter]
