"""Jupyter notebook to Emacs Org-mode and back, using Pandoc"""

import os
import re
import tempfile
from typing import Any, Optional

# Copy nbformat reads and writes to avoid them being patched in the contents manager!!
from nbformat import reads as ipynb_reads
from nbformat import writes as ipynb_writes

from .pandoc import PandocError, pandoc, raise_if_pandoc_is_not_available

# Matches valid Org keyword lines such as #+TITLE:, #+AUTHOR:, #+PROPERTY:, etc.
# Org keywords are case-insensitive; Pandoc may generate lowercase variants.
_ORG_KEYWORD_RE = re.compile(r"^#\+[A-Za-z_]+:", re.IGNORECASE)
_ORG_TARGET_LINE_RE = re.compile(r"(?m)^<<[^>\n]+>>[ \t]*\n?")
_ORG_HEADER_ARGS_RE = re.compile(r"(?im)^#\+PROPERTY:\s*header-args:(jupyter-[^ \t+\n]+)(\+?)\s*(.*)$")
_ORG_HEADER_ARG_RE = re.compile(r":([A-Za-z0-9_-]+)\s+([^:\n]+?)(?=(?:\s+:[A-Za-z0-9_-]+\s)|\s*$)")
_SAFE_HEADER_ARG_RE = re.compile(r"[^A-Za-z0-9_+\-]")


def org_to_notebook(text):
    """Convert an Org-mode text to a Jupyter notebook, using Pandoc"""
    _raise_if_pandoc_is_not_available_for_org()
    metadata = _org_metadata(text)
    text = _strip_org_targets(_strip_org_header_args(text))
    tmp_in = tempfile.NamedTemporaryFile(suffix=".org", delete=False)
    tmp_in.write(text.encode("utf-8"))
    tmp_in.close()
    out_file = tmp_in.name + ".ipynb"

    try:
        pandoc(
            "--from org --to ipynb -s --wrap=preserve --preserve-tabs",
            tmp_in.name,
            out_file,
        )
        with open(out_file, encoding="utf-8") as f:
            notebook = ipynb_reads(f.read(), as_version=4)
    finally:
        os.unlink(tmp_in.name)
        if os.path.exists(out_file):
            os.unlink(out_file)

    notebook.metadata.update(metadata)

    return notebook


def notebook_to_org(notebook):
    """Convert a notebook to its Org-mode representation, using Pandoc"""
    _raise_if_pandoc_is_not_available_for_org()
    tmp_in = tempfile.NamedTemporaryFile(suffix=".ipynb", delete=False)
    tmp_in.write(ipynb_writes(notebook).encode("utf-8"))
    tmp_in.close()
    out_file = tmp_in.name + ".org"

    try:
        pandoc(
            "--from ipynb --to org -s --wrap=preserve --preserve-tabs",
            tmp_in.name,
            out_file,
        )
        with open(out_file, encoding="utf-8") as f:
            text = f.read()
    finally:
        os.unlink(tmp_in.name)
        if os.path.exists(out_file):
            os.unlink(out_file)

    kernelspec = notebook.metadata.get("kernelspec", {})
    kernel_name = _sanitize_header_arg(kernelspec.get("name"))
    kernel_language = _sanitize_header_arg(kernelspec.get("language"))
    if kernel_name and kernel_language:
        text = _inject_kernel_header_args(
            text,
            kernel_name,
            kernel_language,
            notebook.metadata.get("org_babel", {}).get("header_args", {}),
        )

    # Normalize line endings (consistent with pandoc.py behavior)
    return "\n".join(text.splitlines())


def _inject_kernel_header_args(
    text: str,
    kernel_name: str,
    kernel_language: str,
    header_args: dict[str, dict[str, Any]],
) -> str:
    """Insert Org Babel header-args properties near the top of the document.

    Args:
        text: The Org document generated by Pandoc.
        kernel_name: The Jupyter kernelspec name.
        kernel_language: The Jupyter kernelspec language.
        header_args: Additional Org Babel header args keyed by block language.

    Returns:
        The Org document with one ``:kernel`` property line and, when present,
        one concatenated property line for additional header args.
    """
    block_language = f"jupyter-{kernel_language}"
    extra_args = {
        key: _sanitize_header_arg(value) for key, value in header_args.get(block_language, {}).items() if key != "kernel"
    }
    extra_args = {key: value for key, value in extra_args.items() if value}
    if not extra_args:
        extra_args = {"session": kernel_name}

    header_args_lines = [
        _format_header_args_line(block_language, {"kernel": kernel_name}),
    ]
    if extra_args:
        header_args_lines.append(_format_header_args_line(block_language + "+", extra_args))

    lines = text.splitlines(keepends=True)
    last_header_line = -1
    for i, line in enumerate(lines):
        if _ORG_KEYWORD_RE.match(line):
            last_header_line = i
        elif line.strip():
            break

    insert_pos = last_header_line + 1
    lines[insert_pos:insert_pos] = header_args_lines
    return "".join(lines)


def _sanitize_header_arg(value: Any) -> Optional[str]:
    """Restrict an Org header arg value to a conservative safe subset.

    Args:
        value: A metadata value that may be serialized into an Org property.

    Returns:
        The sanitized string value, or ``None`` when no safe value remains.
    """
    if not value:
        return None
    value = str(value)
    value = _SAFE_HEADER_ARG_RE.sub("", value)
    return value or None


def _format_header_args_line(block_language: str, args: dict[str, str]) -> str:
    """Format an Org Babel ``#+PROPERTY: header-args`` line.

    Args:
        block_language: The Org Babel language key, e.g. ``jupyter-python``.
        args: Header args to serialize on that property line.

    Returns:
        A single ``#+PROPERTY`` line terminated by ``\\n``.
    """
    args_text = " ".join(f":{key} {value}" for key, value in args.items())
    return f"#+PROPERTY: header-args:{block_language} {args_text}\n"


def _strip_org_targets(text):
    """Remove standalone Org targets that Pandoc round-trips as HTML anchors."""
    return _ORG_TARGET_LINE_RE.sub("", text)


def _strip_org_header_args(text: str) -> str:
    """Remove Org Babel header-args property lines before Pandoc conversion.

    Args:
        text: The original Org document.

    Returns:
        The Org document with ``header-args`` properties removed so they do not
        become notebook cells during Pandoc conversion.
    """
    return re.sub(r"(?im)^#\+PROPERTY:\s*header-args:[^\n]*\n?", "", text)


def _org_metadata(text: str) -> dict[str, Any]:
    """Extract notebook metadata from Org Babel header-args properties.

    Args:
        text: The original Org document.

    Returns:
        A notebook metadata dictionary containing ``kernelspec`` when a
        ``:kernel`` header arg is present, plus ``org_babel.header_args`` for
        any additional per-language Org Babel header arguments.
    """
    kernelspec = {}
    header_args = {}

    for match in _ORG_HEADER_ARGS_RE.finditer(text):
        block_language = match.group(1)
        parsed_args = {key: value.strip() for key, value in _ORG_HEADER_ARG_RE.findall(match.group(3))}

        if block_language.startswith("jupyter-") and "language" not in kernelspec:
            kernelspec["language"] = block_language.removeprefix("jupyter-")

        kernel_name = parsed_args.pop("kernel", None)
        if kernel_name:
            kernelspec["name"] = kernel_name

        if parsed_args:
            header_args.setdefault(block_language, {}).update(parsed_args)

    metadata = {}

    if header_args:
        metadata["org_babel"] = {"header_args": header_args}

    if not kernelspec:
        return metadata

    if "name" in kernelspec and "display_name" not in kernelspec:
        kernelspec["display_name"] = kernelspec["name"]

    metadata["kernelspec"] = kernelspec
    return metadata


def _raise_if_pandoc_is_not_available_for_org() -> None:
    """Raise with an Org-specific error when Pandoc is unavailable."""
    try:
        raise_if_pandoc_is_not_available()
    except PandocError as exc:
        raise PandocError(str(exc).replace("Pandoc Markdown format", "Pandoc Org format")) from exc
