name: CI
on:
  workflow_dispatch:
    inputs:
      upload-build-artifacts:
        type: boolean
        required: false
        default: false
        description: Upload build artifacts
  push:
    paths-ignore:
      - "CHANGELOG.md"
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 11 * * 4"

permissions:
  # All nested workflows will inherit these permissions and so no need to declare
  # in each step file
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zizmor:
    uses: ./.github/workflows/step_zizmor.yml

  pre-commit:
    uses: ./.github/workflows/step_pre-commit.yml

  static-analysis:
    uses: ./.github/workflows/step_static-analysis.yml
    permissions:
      contents: read
      security-events: write

  coverage:
    uses: ./.github/workflows/step_coverage.yml

  test-pip:
    needs: [ coverage ]
    uses: ./.github/workflows/step_tests-pip.yml

  test-conda:
    needs: [ coverage ]
    uses: ./.github/workflows/step_tests-conda.yml

  test-ui:
    needs: [ coverage ]
    uses: ./.github/workflows/step_tests-ui.yml

  build:
    needs: [ coverage ]
    uses: ./.github/workflows/step_build.yml
    with:
      upload: ${{ inputs.upload-build-artifacts || false }}

  pass:
    name: Pass
    needs: [ zizmor, pre-commit, static-analysis, test-pip, coverage, test-conda, test-ui, build ]
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
          allowed-skips: coverage
    if: always()
