name: pre-commit
run-name: Run pre-commit tests

on:
  workflow_call:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: "3.x"

      - name: Install pixi
        uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11 # v0.9.6
        with:
          pixi-version: v0.68.0
          cache: true
          activate-environment: true

      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

  lint-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@95d85449e4f3f352e261221f6529f8ed307f5728 # v1
        with:
          python_version: "3.x"

      # Current repo organization will not permit to set up pre-commit config for
      # TS lint related packages due to absence of package.json in the top level
      # repo. So we run lint step separately here
      - name: Lint the extension
        run: |
          # Install JupyterLab in an isolated env to get jlpm
          pip install jupyterlab>=4

          # Install lint deps and lint extension
          cd jupyterlab/
          jlpm
          jlpm run lint:check
