name: coverage
run-name: Check coverage

on:
  workflow_call:

permissions:
  contents: read

jobs:
  coverage:
    name: >
      ${{ matrix.coverage }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        coverage: [unit, functional, integration, external]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
        with:
          python_version: 3.x

      - name: Install from source
        run: python -m pip install -e '.[test-cov,test-${{ matrix.coverage }}]'

      - name: Install a Jupyter Kernel
        run: python -m ipykernel install --name python_kernel --user

      - name: Run the tests
        run: pytest tests/${{ matrix.coverage }} -n logical --cov --cov-report=xml

      - name: Upload the coverage
        uses: codecov/codecov-action@v3
        with:
          flags: ${{ matrix.coverage }}
          fail_ci_if_error: true
          verbose: true
