name: build
run-name: Build package

on:
  workflow_call:
    inputs:
      upload:
        type: boolean
        required: false
        default: false
        description: Upload build artifacts
      ref:
        type: string
        description: Tag to build

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false

      - name: Install pixi
        uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11 # v0.9.6
        with:
          pixi-version: v0.68.0
          cache: true
          activate-environment: default
          environments: "default build"

      - name: Build JupyterLab extension
        run: pixi run -e build build-labextension

      - name: Build package
        run: HATCH_BUILD_HOOKS_ENABLE=true hatch build

      - name: Archive build artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: dist
          path: dist
        if: ${{ inputs.upload }}
