name: test-categories
run-name: Run Unit/Functional/Integration and External tests using Pip

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-test_classification
  cancel-in-progress: true

jobs:
  test-pip:
    continue-on-error: ${{ matrix.experimental || false }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
        with:
          python_version: ${{ matrix.python-version }}

      - name: Install from source
        run: python -m pip install -e '.[test-cov]' markdown-it-py~=3.0

      - name: Run the unit tests
        run: pytest tests/unit --cov=src/jupytext --cov-report=xml

      - name: Run the functional tests
        run: pytest tests/functional --cov=src/jupytext --cov-report=xml

      - name: Install the integration test dependencies
        run: python -m pip install -e '.[test-integration]'

      - name: Install a Jupyter Kernel
        run: python -m ipykernel install --name python_kernel --user

      - name: Run the integration tests
        run: pytest tests/integration --cov=src/jupytext --cov-report=xml

      - name: Install the external test dependencies
        run: python -m pip install -e '.[test-external]'

      - name: Run the external tests
        run: pytest tests/external --cov=src/jupytext --cov-report=xml

      - name: Upload the coverage
        uses: codecov/codecov-action@v3
